apiVersion: v1
kind: Service
metadata:
  name: curl-svc
spec:
  ports:
  - port: 27018
  selector:
    app: curl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
spec:
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - image: "{{ .Values.curl.image.repository }}:{{ .Values.curl.image.tag }}"
        name: curl
        args: "{{ .Values.curl.command }}"
        ports:
        - containerPort: 27018
          name: curl
